name: CI/CD pipeline for TaskSync backend Azure VM

on:
  push:
    branches: [ master ]

  pull_request:
    types: [closed]
    branches: [ master ] # Merge to master branch


jobs:
  docker: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Build and push Docker image
      uses: docker/build-push-action@v6


    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/ts-frontend:latest